feat: add context for additional JWT data
honestbank/mfa-lib pull request #5
Opened 2022-03-07 13:22 UTC by bludot

### Description

* Add call to resolve when all challenges have been solved

2022-03-07 13:24 UTC, smashdown approved these changes

2022-03-08 03:32 UTC, cyberhck requested changes

2022-03-08 03:32 UTC, cyberhck commented on mfa/mfa.go
> +	}
flip the logic :)

2022-03-08 03:34 UTC, cyberhck approved these changes

2022-03-08 03:36 UTC, merged